
package us.kbase.workspaceservice;

import java.util.HashMap;
import java.util.Map;
import javax.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import us.kbase.common.service.Tuple11;
import us.kbase.common.service.UObject;


/**
 * <p>Original spec-file type: get_object_output</p>
 * <pre>
 * Output generated by the "get_object" function.
 *         string data - data for object retrieved in json format (an essential argument)
 *         object_metadata metadata - metadata for object retrieved (an essential argument)
 * </pre>
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("com.googlecode.jsonschema2pojo")
@JsonPropertyOrder({
    "data",
    "metadata"
})
public class GetObjectOutput {

    @JsonProperty("data")
    private Object data;
    @JsonProperty("metadata")
    private Tuple11 <String, String, String, Long, String, String, String, String, String, String, Map<String, Object>> metadata;
    private Map<java.lang.String, Object> additionalProperties = new HashMap<java.lang.String, Object>();

    @JsonProperty("data")
    public Object getData() {
        return data;
    }

    @JsonProperty("data")
    public void setData(Object data) {
        this.data = data;
    }

    public GetObjectOutput withData(Object data) {
        this.data = data;
        return this;
    }

    @JsonProperty("metadata")
    public Tuple11 <String, String, String, Long, String, String, String, String, String, String, Map<String, Object>> getMetadata() {
        return metadata;
    }

    @JsonProperty("metadata")
    public void setMetadata(Tuple11 <String, String, String, Long, String, String, String, String, String, String, Map<String, Object>> metadata) {
        this.metadata = metadata;
    }

    public GetObjectOutput withMetadata(Tuple11 <String, String, String, Long, String, String, String, String, String, String, Map<String, Object>> metadata) {
        this.metadata = metadata;
        return this;
    }

    @JsonAnyGetter
    public Map<java.lang.String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperties(java.lang.String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        return ((((((("GetObjectOutput"+" [data=")+ data)+", metadata=")+ metadata)+", additionalProperties=")+ additionalProperties)+"]");
    }

}
